import type { TrainingProgram } from './types';

export const DEFAULT_PROGRAM: TrainingProgram = {
  warmup:
    '- 5 min dynamic mobility (hips, shoulders, thoracic spine)\n- 2 light ramp-up sets for first two strength movements',
  workout: [
    {
      id: 'ex-1',
      title: 'Zgib (siroki/uski rotirano)',
      description: 'Bodyweight pull-up variation with rotating grip focus.',
      sets: '4',
      reps: '5',
      weight: 'Bodyweight',
      rest: '90',
      bodyPart: 'back',
    },
    {
      id: 'ex-2',
      title: 'Leg press',
      description: 'Increased load, strength focus.',
      sets: '4',
      reps: '8',
      weight: '80-90 kg',
      rest: '120',
      bodyPart: 'legs',
    },
    {
      id: 'ex-3',
      title: 'Veslanje (sprava, neutralni hvat)',
      description: 'Machine row with neutral grip.',
      sets: '4',
      reps: '10',
      weight: '45-55 kg',
      rest: '90',
      bodyPart: 'back',
    },
    {
      id: 'ex-4',
      title: 'Chest press (sprava ili sklekovi)',
      description: 'Upper body balance movement.',
      sets: '3',
      reps: '10',
      weight: 'Moderate',
      rest: '75',
      bodyPart: 'chest',
    },
    {
      id: 'ex-5',
      title: 'Letenje (bucice)',
      description: 'Controlled fly movement.',
      sets: '3',
      reps: '15',
      weight: '2-3 kg',
      rest: '60',
      bodyPart: 'shoulders',
    },
    {
      id: 'ex-6',
      title: 'Leg curl (kick)',
      description: 'Hamstring isolation.',
      sets: '3-4',
      reps: '10',
      weight: '40 kg',
      rest: '75',
      bodyPart: 'legs',
    },
    {
      id: 'ex-7',
      title: 'Ekstenzija noge',
      description: 'Leg extension machine.',
      sets: '3',
      reps: '12',
      weight: '45 kg',
      rest: '75',
      bodyPart: 'legs',
    },
    {
      id: 'ex-8',
      title: 'Biceps hammer (neutralni hvat)',
      description: 'Neutral grip dumbbell curl.',
      sets: '3',
      reps: '10-12',
      weight: '5-6 kg',
      rest: '60',
      bodyPart: 'biceps',
    },
    {
      id: 'ex-9',
      title: 'Triceps pushdown (sajla/uze)',
      description: 'Cable rope pushdown.',
      sets: '3',
      reps: '10-12',
      weight: '10-15 kg',
      rest: '60',
      bodyPart: 'triceps',
    },
    {
      id: 'ex-10',
      title: 'Plank (na podlakticama)',
      description: 'Forearm plank hold.',
      sets: '3',
      reps: '45 sec',
      weight: 'Bodyweight',
      rest: '45',
      bodyPart: 'core',
    },
  ],
  cardio: [
    { id: 'cardio-1', exercise: 'Incline treadmill walk', time: '12 min' },
    { id: 'cardio-2', exercise: 'Bike easy spin', time: '8 min' },
  ],
  cooldown:
    '- 5 min easy walk + nasal breathing\n- Light static stretch for chest, lats, quads, hamstrings',
  notes:
    'Target quality reps. Keep 1-2 reps in reserve on compound lifts. If energy drops, prioritize exercise #1-#4.',
};
